"""Portfolio accounting: cash, signed positions, average cost and PnL attribution.

Accounting identities maintained at all times (verified by property-based tests)::

    equity = cash + sum(quantity * mark_price)
    equity = initial_cash + realized_pnl + unrealized_pnl - commissions - borrow_costs

``realized_pnl`` and ``unrealized_pnl`` are gross of costs; commissions and borrow
fees are tracked separately so their drag is visible in reports. Slippage is already
embedded in fill prices and therefore in the PnL figures.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Mapping
from dataclasses import dataclass

from backtester.errors import ConfigError
from backtester.events import FillEvent

_EPS = 1e-9


@dataclass(slots=True)
class Position:
    """A signed position in one symbol (negative quantity means short)."""

    symbol: str
    quantity: float = 0.0
    avg_cost: float = 0.0
    realized_pnl: float = 0.0
    last_price: float = math.nan

    @property
    def is_flat(self) -> bool:
        """Whether the position is (numerically) zero."""
        return abs(self.quantity) <= _EPS

    @property
    def market_value(self) -> float:
        """Signed ``quantity * last_price`` (0 when flat or never priced)."""
        quantity, price = self.quantity, self.last_price
        if -_EPS <= quantity <= _EPS or math.isnan(price):  # flat, or never priced
            return 0.0
        return quantity * price

    @property
    def unrealized_pnl(self) -> float:
        """Gross PnL of the open quantity versus its average cost."""
        if self.is_flat or math.isnan(self.last_price):
            return 0.0
        return self.quantity * (self.last_price - self.avg_cost)

    def apply_fill(self, signed_quantity: float, price: float) -> float:
        """Update the position for a fill and return the realized PnL it produced.

        Increasing a position moves the average cost; reducing it realizes
        ``(price - avg_cost) * closed_quantity`` (sign-adjusted for shorts); crossing
        through zero closes the old position and opens the remainder at ``price``.
        """
        old = self.quantity
        new = old + signed_quantity
        realized = 0.0
        if abs(old) <= _EPS or old * signed_quantity > 0:
            # Opening or adding in the same direction.
            total = abs(old) + abs(signed_quantity)
            self.avg_cost = (abs(old) * self.avg_cost + abs(signed_quantity) * price) / total
        else:
            closed = min(abs(signed_quantity), abs(old))
            direction = 1.0 if old > 0 else -1.0
            realized = (price - self.avg_cost) * closed * direction
            if abs(new) <= _EPS:
                new = 0.0
                self.avg_cost = 0.0
            elif new * old < 0:
                self.avg_cost = price  # flipped: remainder opened at the fill price
        self.quantity = new
        self.realized_pnl += realized
        return realized


class Portfolio:
    """Cash and positions of a single-currency account.

    Negative cash is allowed (margin); leverage is controlled by the risk manager.
    """

    def __init__(self, initial_cash: float, symbols: Iterable[str] = ()) -> None:
        if not math.isfinite(initial_cash) or initial_cash <= 0:
            raise ConfigError("initial_cash must be a positive finite number")
        self.initial_cash = float(initial_cash)
        self.cash = float(initial_cash)
        self.positions: dict[str, Position] = {s: Position(s) for s in symbols}
        self.realized_pnl = 0.0
        self.total_commission = 0.0
        self.total_slippage = 0.0
        self.total_borrow_cost = 0.0
        self.traded_notional = 0.0
        self.fill_count = 0

    def position(self, symbol: str) -> Position:
        """The position in ``symbol`` (created flat on first access)."""
        pos = self.positions.get(symbol)
        if pos is None:
            pos = self.positions[symbol] = Position(symbol)
        return pos

    def quantity(self, symbol: str) -> float:
        """Signed quantity held in ``symbol``."""
        pos = self.positions.get(symbol)
        return 0.0 if pos is None else pos.quantity

    # ------------------------------------------------------------------ updates
    def on_fill(self, fill: FillEvent) -> float:
        """Apply a fill: move cash, update the position, book commission.

        Returns:
            The realized PnL (gross of commission) generated by the fill.
        """
        signed = fill.signed_quantity
        self.cash -= signed * fill.price + fill.commission
        pos = self.position(fill.symbol)
        realized = pos.apply_fill(signed, fill.price)
        if math.isnan(pos.last_price):
            pos.last_price = fill.price
        self.realized_pnl += realized
        self.total_commission += fill.commission
        self.total_slippage += fill.slippage
        self.traded_notional += fill.notional
        self.fill_count += 1
        return realized

    def mark(self, prices: Mapping[str, float]) -> None:
        """Mark positions to the given prices (NaN prices are ignored)."""
        for symbol, price in prices.items():
            if math.isnan(price):
                continue
            pos = self.positions.get(symbol)
            if pos is None:
                pos = self.positions[symbol] = Position(symbol)
            pos.last_price = float(price)

    def charge_borrow(self, annual_rate: float, year_fraction: float) -> float:
        """Debit a borrow fee on the market value of short positions; return the fee."""
        if annual_rate <= 0:
            return 0.0
        short_value = -sum(min(p.market_value, 0.0) for p in self.positions.values())
        fee = short_value * annual_rate * year_fraction
        self.cash -= fee
        self.total_borrow_cost += fee
        return fee

    # ------------------------------------------------------------------ valuation
    @property
    def market_value(self) -> float:
        """Net market value of all positions."""
        return sum([p.market_value for p in self.positions.values()])

    @property
    def equity(self) -> float:
        """Net liquidation value: ``cash + sum(quantity * price)``."""
        return self.cash + self.market_value

    @property
    def unrealized_pnl(self) -> float:
        """Gross unrealized PnL across positions."""
        return sum(p.unrealized_pnl for p in self.positions.values())

    @property
    def gross_exposure(self) -> float:
        """Sum of absolute position values."""
        return sum([abs(p.market_value) for p in self.positions.values()])

    @property
    def net_exposure(self) -> float:
        """Sum of signed position values."""
        return self.market_value

    @property
    def leverage(self) -> float:
        """Gross exposure divided by equity (``inf`` if equity <= 0)."""
        eq = self.equity
        return self.gross_exposure / eq if eq > 0 else math.inf

    def weights(self) -> dict[str, float]:
        """Signed position weights as fractions of equity."""
        eq = self.equity
        if eq <= 0:
            return dict.fromkeys(self.positions, 0.0)
        return {s: p.market_value / eq for s, p in self.positions.items()}

    def identity_error(self) -> float:
        """Absolute discrepancy between the two equity identities (should be ~0)."""
        via_pnl = (
            self.initial_cash
            + self.realized_pnl
            + self.unrealized_pnl
            - self.total_commission
            - self.total_borrow_cost
        )
        return abs(self.equity - via_pnl)
